name: Patr keepalive

on:
  schedule:
    # UTC (国内 UTC+8)
    - cron: '1 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python -m playwright install
    - name: Login to patr for reboot deployment
      env:
        PATR_USERNAME: ${{ secrets.PATR_USERNAME }}
        PATR_PASSWORD: ${{ secrets.PATR_PASSWORD }}
      run: |
        python patr.py
